### ISSUE TITLE
ks matrix in cp2k-7.1  go to infinite value error with broyden mixing 

### ISSUE THREAD

**Issue by robinzyb** [cp2k/cp2k#1057]
Dear developers,
         I compiled cp2k-7.1 in centos 8 with gcc-8.3.1 and openmpi 4.0.2, which all is installed from yum.
         The input which run correctly in cp2k-4.1 and cp2k-6.1 failed in cp2k-7.1 sopt and popt version
         
```
==============ERROR MESSAGE====================
Step     Update method      Time    Convergence         Total energy    Change
  ------------------------------------------------------------------------------
     1 NoMix/Diag. 0.20E+00    0.8     0.49323947      -387.7762656335 -3.88E+02
     2 Broy./Diag. 0.20E+00    1.3     0.02424614      -387.2928316904  4.83E-01
     3 Broy./Diag. 0.20E+00    1.4     0.04722192      -386.5284198804  7.64E-01
     4 Broy./Diag. 0.20E+00    1.4     0.00877451      -386.4513390785  7.71E-02

 *******************************************************************************
 *   ___                                                                       *
 *  /   \                                                                      *
 * [ABORT]                                                                     *
 *  \___/                KS energy is an abnormal value (NaN/Inf).             *
 *    |                                                                        *
 *  O/|                                                                        *
 * /| |                                                                        *
 * / \                                                     qs_ks_methods.F:870 *
 *******************************************************************************


 ===== Routine Calling Stack =====

            9 qs_ks_build_kohn_sham_matrix
            8 rebuild_ks_matrix
            7 qs_ks_update_qs_env
            6 scf_env_do_scf_inner_loop
            5 scf_env_do_scf
            4 qs_energies
            3 qs_forces
            2 qs_mol_dyn_low
            1 CP2K
Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x7f575d2bb131 in ???
#1  0x7f575d2ba2d3 in ???
#2  0x7f575c73595f in ???
#3  0x7f575c7358df in ???
#4  0x7f575c71fcf4 in ???
#5  0x240ad98 in __message_passing_MOD_mp_abort
	at /opt/software/cp2k-7.1/src/mpiwrap/message_passing.F:1075
#6  0x240c074 in __base_hooks_MOD_cp_abort
	at /opt/software/cp2k-7.1/src/base/base_hooks.F:74
#7  0x240c21b in __base_hooks_MOD_cp__b
	at /opt/software/cp2k-7.1/src/base/base_hooks.F:178
#8  0xdf1b78 in __qs_ks_methods_MOD_qs_ks_build_kohn_sham_matrix
	at /opt/software/cp2k-7.1/src/qs_ks_methods.F:870
#9  0xdf396f in rebuild_ks_matrix
	at /opt/software/cp2k-7.1/src/qs_ks_methods.F:1215
#10  0xdf396f in __qs_ks_methods_MOD_qs_ks_update_qs_env
	at /opt/software/cp2k-7.1/src/qs_ks_methods.F:1120
#11  0x11a3d2e in __qs_scf_MOD_scf_env_do_scf
	at /opt/software/cp2k-7.1/src/qs_scf.F:441
#12  0x11b0280 in __qs_scf_MOD_scf
	at /opt/software/cp2k-7.1/src/qs_scf.F:233
#13  0xaae3ca in __qs_energy_MOD_qs_energies
	at /opt/software/cp2k-7.1/src/qs_energy.F:86
#14  0xf72c3f in qs_forces
	at /opt/software/cp2k-7.1/src/qs_force.F:208
#15  0xf759f7 in __qs_force_MOD_qs_calc_energy_force
	at /opt/software/cp2k-7.1/src/qs_force.F:113
#16  0x7b6bdc in __force_env_methods_MOD_force_env_calc_energy_force
	at /opt/software/cp2k-7.1/src/force_env_methods.F:261
#17  0x4d2c7a in qs_mol_dyn_low
	at /opt/software/cp2k-7.1/src/motion/md_run.F:371
#18  0x4d353c in __md_run_MOD_qs_mol_dyn
	at /opt/software/cp2k-7.1/src/motion/md_run.F:152
#19  0x411386 in cp2k_run
	at /opt/software/cp2k-7.1/src/start/cp2k_runs.F:363
#20  0x413adb in __cp2k_runs_MOD_run_input
	at /opt/software/cp2k-7.1/src/start/cp2k_runs.F:965
#21  0x407ef1 in cp2k
	at /opt/software/cp2k-7.1/src/start/cp2k.F:296
#22  0x4065dc in main
	at /opt/software/cp2k-7.1/src/start/cp2k.F:45
Aborted (core dumped)

===========================
```

[cp2k-7.1-install-and-input.zip](https://github.com/cp2k/cp2k/files/5130266/cp2k-7.1-install-and-input.zip)

**Comment by robinzyb** [comment]
one more, if I comment out the broyden mixing or change to OT algorithm, the input can run correctly.
