### ISSUE TITLE
makedep.py fails on some machines due to a unicode character

### ISSUE THREAD

**Issue by l00ki** [cp2k/cp2k#1100]
Due to [this snippet](https://github.com/cp2k/cp2k/commit/d3d36bb8a17094ec894bde01ec3cab3f23415d1d), I have experienced compilation errors with fresh clones on some machines. the output is

```
make: Entering directory '/scratch/luschr/git/cp2k'
Discovering programs ...
make -C /scratch/luschr/git/cp2k/exts/dbcsr -f .cp2k/Makefile \
   INCLUDEMAKE=/scratch/luschr/git/cp2k/arch/local.psmp \
   LIBDIR=/scratch/luschr/git/cp2k/lib/local/psmp/exts/dbcsr \
   OBJDIR=/scratch/luschr/git/cp2k/obj/local/psmp/exts/dbcsr \
   ACC="" \
   ACCFLAGS=""
Removing stale archives for psmp ...
Removing stale archives ...
Resolving dependencies ...
Resolving dependencies for psmp ...
Traceback (most recent call last):
  File "/scratch/luschr/git/cp2k/tools/build_utils/makedep.py", line 429, in <module>
    src_files=args.src_file,
  File "/scratch/luschr/git/cp2k/tools/build_utils/makedep.py", line 45, in main
    parse_file(parsed_files, fn, src_dir)  # parses also included files
  File "/scratch/luschr/git/cp2k/tools/build_utils/makedep.py", line 203, in parse_file
    content = fhandle.read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3479: ordinal not in range(128)
/scratch/luschr/git/cp2k/Makefile:448: recipe for target 'makedep' failed
make[2]: *** [makedep] Error 1
/scratch/luschr/git/cp2k/Makefile:126: recipe for target 'psmp' failed
make[1]: *** [psmp] Error 2
Makefile:121: recipe for target 'all' failed
make: *** [all] Error 2
make: Leaving directory '/scratch/luschr/git/cp2k'
```

For now I just changed the character to d, but I am sure we can tell Python to use Unicode decoding?

**Comment by mkrack** [comment]
Recently (see #976) the support for UTF-8 characters was added. It's weird that a fresh clone does not work for you.
