### ISSUE TITLE
Test QS/regtest-kg/H2_H2O-kglri.inp failing with farming and 8 ranks

### ISSUE THREAD

**Issue by alazzaro** [cp2k/cp2k#121]
The test QS/regtest-kg/H2_H2O-kglri.inp, touched in the commit ebf37dd0cddf178f1169564193275c4ab37fbba2,  fails on Daint with the farming regtest for 8 ranks. It doesn't crash when farming is not used and with fewer ranks. The log is:

```
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x599e57f in ???
        at /home/abuild/rpmbuild/BUILD/glibc-2.22/nptl/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
#1  0xbb4af7 in __qs_grid_atom_MOD_initialize_atomic_grid
        at /store/uzh/uzh1/CP2K_AUTO_REGTEST/DAINT/CRAY_XC50-gfortran_mc/psmp/cp2k/src/qs_grid_atom.F:355
#2  0x15dc90f in init_kg_env
        at /store/uzh/uzh1/CP2K_AUTO_REGTEST/DAINT/CRAY_XC50-gfortran_mc/psmp/cp2k/src/kg_environment.F:346
#3  0x1723402 in __qs_environment_MOD_qs_init
        at /store/uzh/uzh1/CP2K_AUTO_REGTEST/DAINT/CRAY_XC50-gfortran_mc/psmp/cp2k/src/qs_environment.F:403
#4  0x1479190 in __f77_interface_MOD_create_force_env
        at /store/uzh/uzh1/CP2K_AUTO_REGTEST/DAINT/CRAY_XC50-gfortran_mc/psmp/cp2k/src/f77_interface.F:790
#5  0x786a06 in cp2k_run
        at /store/uzh/uzh1/CP2K_AUTO_REGTEST/DAINT/CRAY_XC50-gfortran_mc/psmp/cp2k/src/start/cp2k_runs.F:282
#6  0x785f08 in execute_job
        at /store/uzh/uzh1/CP2K_AUTO_REGTEST/DAINT/CRAY_XC50-gfortran_mc/psmp/cp2k/src/start/cp2k_runs.F:835
#7  0x788b13 in farming_run
        at /store/uzh/uzh1/CP2K_AUTO_REGTEST/DAINT/CRAY_XC50-gfortran_mc/psmp/cp2k/src/start/cp2k_runs.F:650
#8  0x788b13 in cp2k_run
        at /store/uzh/uzh1/CP2K_AUTO_REGTEST/DAINT/CRAY_XC50-gfortran_mc/psmp/cp2k/src/start/cp2k_runs.F:268
#9  0x78a44c in __cp2k_runs_MOD_run_input
        at /store/uzh/uzh1/CP2K_AUTO_REGTEST/DAINT/CRAY_XC50-gfortran_mc/psmp/cp2k/src/start/cp2k_runs.F:1111
#10  0x784fe9 in cp2k
        at /store/uzh/uzh1/CP2K_AUTO_REGTEST/DAINT/CRAY_XC50-gfortran_mc/psmp/cp2k/src/start/cp2k.F:281
#11  0x78125c in main

```
For the time being, I have removed the test from Daint.

**Comment by alazzaro** [comment]
Closing this issue because it is not possible to reproduce it anymore.
