### ISSUE TITLE
Error running CP2K with NVIDIA A100 on HPC environment

### ISSUE THREAD

**Issue by vidaldominguez** [cp2k/cp2k#3379]
Hi everybody,

I'm trying to run CP2K in an HPC environment and using **NVIDIA A100** graphics cards and **slurm** as job scheduling but I'm having some problems.

I am using **version 2024.1** and the **build is successful**.  

This is my environment:

- SO: Rocky 8.6
- GCC/11.3.0
- OpenMPI/4.1.4-GCC-11.3.0
- binutils/2.38
- zlib/1.2.12
- PMIx/4.1.2  -  PMI Exascale (PMIx)
- OpenBLAS/0.3.20
- FlexiBLAS/3.2.0
- ScaLAPACK/2.2.0
- CMake/3.24.3
- FFTW/3.3.10
- FFTW.MPI/3.3.10
- CUDA/11.8.0

These are the steps I followed according your documentation:

I launch toolchain script with this options: *enable-cuda and gpu-ver*, some system libraries and without any optional libraries or plugins.
(I tried to compile without the system libraries but without success)

```
./install_cp2k_toolchain.sh --enable-cuda --gpu-ver=A100 --with-cmake=system --with-openblas=system --with-scalapack=system --with-fftw=system --with-elpa=no  --with-sirius=no --with-gsl=no --with-libvdwxc=no --with-hdf5=no --with-spfft=no --with-spla=no --with-cosma=no 
```
The generated prebuild arch file are:

```shell
arch/
├── local_asan.psmp
├── local_asan.ssmp
├── local_coverage_cuda.pdbg
├── local_coverage.pdbg
├── local_coverage.sdbg
├── local_cuda.pdbg
├── local_cuda.psmp
├── local_cuda.sdbg
├── local_cuda.ssmp
├── local_cuda_warn.psmp
├── local.pdbg
├── local.psmp
├── local.sdbg
├── local.ssmp
├── local_static.psmp
├── local_static.ssmp
└── local_warn.psmp
```

I use the *local_cuda.psmp* to compile cp2k using this sentence `make -j ARCH=local_cuda VERSION=psmp` 
```makefile
CC          = /share/myuser/software/x86_64/software/OpenMPI/4.1.4-GCC-11.3.0/bin/mpicc
CXX         = /share/myuser/software/x86_64/software/OpenMPI/4.1.4-GCC-11.3.0/bin/mpic++
AR          = ar -r
FC          = /share/myuser/software/x86_64/software/OpenMPI/4.1.4-GCC-11.3.0/bin/mpifort
LD          = /share/myuser/software/x86_64/software/OpenMPI/4.1.4-GCC-11.3.0/bin/mpifort
#
DFLAGS      = -D__OFFLOAD_CUDA -D__DBCSR_ACC  -D__LIBXSMM  -D__parallel -D__MPI_F08 -D__FFTW3  -D__LIBINT -D__LIBXC -D__LIBGRPP -D__SCALAPACK -D__SPGLIB -D__LIBVORI
#
WFLAGS      = -Werror=aliasing -Werror=ampersand -Werror=c-binding-type -Werror=intrinsic-shadow -Werror=intrinsics-std -Werror=line-truncation -Werror=tabs -Werror=target-lifetime -Werror=underflow -Werror=unused-but-set-variable -Werror=unused-variable -Werror=unused-dummy-argument -Werror=unused-parameter -Werror=unused-label -Werror=conversion -Werror=zerotrip -Wno-maybe-uninitialized -Wuninitialized -Wuse-without-only
#
FCDEBFLAGS  = -fbacktrace -ffree-form -fimplicit-none -std=f2008
CFLAGS      = -fno-omit-frame-pointer -fopenmp -g -mtune=native  -O3 -funroll-loops $(PROFOPT)  -I/share/myuser/software/x86_64/software/OpenMPI/4.1.4-GCC-11.3.0/include  -I'/share/myuser/software/x86_64/software/OpenBLAS/0.3.20-GCC-11.3.0/include' -I'/share/myuser/software/x86_64/software/FFTW.MPI/3.3.10-gompi-2022a/include' -I'/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libint-v2.6.0-cp2k-lmax-5/include' -I'/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libxc-6.2.2/include' -I'/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libgrpp-main-20231215/include' -I'/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libxsmm-1.17/include' -I/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/spglib-1.16.2/include -std=c11 -Wall -Wextra -Werror -Wno-vla-parameter -Wno-deprecated-declarations $(DFLAGS) -I/share/myuser/software/x86_64/software/CUDA/11.8.0/include
FCFLAGS     = -fno-omit-frame-pointer -fopenmp -g -mtune=native  -O3 -funroll-loops $(PROFOPT)  -I/share/myuser/software/x86_64/software/OpenMPI/4.1.4-GCC-11.3.0/include  -I'/share/myuser/software/x86_64/software/OpenBLAS/0.3.20-GCC-11.3.0/include' -I'/share/myuser/software/x86_64/software/FFTW.MPI/3.3.10-gompi-2022a/include' -I'/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libint-v2.6.0-cp2k-lmax-5/include' -I'/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libxc-6.2.2/include' -I'/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libgrpp-main-20231215/include' -I'/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libxsmm-1.17/include' -I/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/spglib-1.16.2/include $(FCDEBFLAGS) $(WFLAGS) $(DFLAGS) -fallow-argument-mismatch
CXXFLAGS    = -O2 -fPIC -fno-omit-frame-pointer -fopenmp -g -march=native -mtune=native --std=c++14 $(DFLAGS) -Wno-deprecated-declarations -I/share/myuser/software/x86_64/software/CUDA/11.8.0/include
#
LDFLAGS     =  $(FCFLAGS) -Wl,--enable-new-dtags -L/share/myuser/software/x86_64/software/OpenMPI/4.1.4-GCC-11.3.0/lib -L/share/myuser/software/x86_64/software/hwloc/2.7.1-GCCcore-11.3.0/lib -L/share/myuser/software/x86_64/software/libevent/2.1.12-GCCcore-11.3.0/lib -Wl,-rpath -Wl,/share/myuser/software/x86_64/software/OpenMPI/4.1.4-GCC-11.3.0/lib -Wl,-rpath -Wl,/share/myuser/software/x86_64/software/hwloc/2.7.1-GCCcore-11.3.0/lib -Wl,-rpath -Wl,/share/myuser/software/x86_64/software/libevent/2.1.12-GCCcore-11.3.0/lib -Wl,--enable-new-dtags   -L'/share/myuser/software/x86_64/software/OpenBLAS/0.3.20-GCC-11.3.0/lib' -Wl,-rpath,'/share/myuser/software/x86_64/software/OpenBLAS/0.3.20-GCC-11.3.0/lib' -L'/share/myuser/software/x86_64/software/FFTW.MPI/3.3.10-gompi-2022a/lib' -Wl,-rpath,'/share/myuser/software/x86_64/software/FFTW.MPI/3.3.10-gompi-2022a/lib' -L'/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libint-v2.6.0-cp2k-lmax-5/lib' -L'/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libxc-6.2.2/lib' -Wl,-rpath,'/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libxc-6.2.2/lib' -L'/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libgrpp-main-20231215/lib' -Wl,-rpath,'/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libgrpp-main-20231215/lib' -L'/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libxsmm-1.17/lib' -Wl,-rpath,'/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libxsmm-1.17/lib' -L'/share/myuser/software/x86_64/software/ScaLAPACK/2.2.0-gompi-2022a-fb/lib' -Wl,-rpath,'/share/myuser/software/x86_64/software/ScaLAPACK/2.2.0-gompi-2022a-fb/lib' -L'/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/spglib-1.16.2/lib' -Wl,-rpath,'/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/spglib-1.16.2/lib' -L'/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libvori-220621/lib' -Wl,-rpath,'/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libvori-220621/lib' -L'/share/myuser/software/x86_64/software/CUDA/11.8.0/targets/x86_64-linux/lib' -Wl,-rpath,'/share/myuser/software/x86_64/software/CUDA/11.8.0/targets/x86_64-linux/lib' -L'/share/myuser/software/x86_64/software/CUDA/11.8.0/stubs/lib64' -Wl,-rpath,'/share/myuser/software/x86_64/software/CUDA/11.8.0/stubs/lib64'
LDFLAGS_C   =
LIBS        = -lsymspg -lscalapack -lxsmmf -lxsmm -ldl -lpthread -llibgrpp -lxcf03 -lxc -lint2 -lfftw3_mpi -lfftw3 -lfftw3_omp   -lmpi  -lopenblas -lvori -lstdc++ -lstdc++ -lcudart -lnvrtc -lcuda -lcufft -lcublas -lrt
#
GPUVER        = A100
OFFLOAD_CC    = nvcc
OFFLOAD_FLAGS = -g -arch sm_80 -O3 -allow-unsupported-compiler -Xcompiler='-fopenmp -Wall -Wextra -Werror' --std=c++11 $(DFLAGS) -I'/share/myuser/software/x86_64/software/CUDA/11.8.0/targets/x86_64-linux/include'
OFFLOAD_TARGET = cuda
#
FYPPFLAGS   = -n --line-marker-format=gfortran5
```

Load the setup file: 

> source cp2k_repogit/tool/toolchain/install/setup

```shell
#!/bin/bash
source "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/scripts/tool_kit.sh" 
export CP2K_TOOLCHAIN_OPTIONS="--enable-cuda --gpu-ver=A100 --with-cmake=system --with-openblas=system --with-scalapack=system --with-fftw=system --with-elpa=no --with-sirius=no --with-gsl=no --with-libvdwxc=no --with-hdf5=no --with-spfft=no --with-spla=no --with-cosma=no" 
export CC="/share/myuser/software/x86_64/software/GCCcore/11.3.0/bin/gcc" 
export CXX="/share/myuser/software/x86_64/software/GCCcore/11.3.0/bin/g++" 
export FC="/share/myuser/software/x86_64/software/GCCcore/11.3.0/bin/gfortran" 
export F90="/share/myuser/software/x86_64/software/GCCcore/11.3.0/bin/gfortran" 
export F77="/share/myuser/software/x86_64/software/GCCcore/11.3.0/bin/gfortran" 
export GCC_CFLAGS="-I'/usr/include'" 
export GCC_LDFLAGS="-L'/share/myuser/software/x86_64/software/GCCcore/11.3.0/lib64' -Wl,-rpath,'/share/myuser/software/x86_64/software/GCCcore/11.3.0/lib64'" 
export TSANFLAGS="" 
export LSAN_OPTIONS=suppressions=/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/lsan.supp
export TSAN_OPTIONS=suppressions=/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/tsan.supp
export MPI_MODE="openmpi" 
export MPIRUN="/share/myuser/software/x86_64/software/OpenMPI/4.1.4-GCC-11.3.0/bin/mpiexec" 
export MPICC="/share/myuser/software/x86_64/software/OpenMPI/4.1.4-GCC-11.3.0/bin/mpicc" 
export MPICXX="/share/myuser/software/x86_64/software/OpenMPI/4.1.4-GCC-11.3.0/bin/mpic++" 
export MPIFC="/share/myuser/software/x86_64/software/OpenMPI/4.1.4-GCC-11.3.0/bin/mpifort" 
export MPIFORT="/share/myuser/software/x86_64/software/OpenMPI/4.1.4-GCC-11.3.0/bin/mpifort" 
export MPIF77="/share/myuser/software/x86_64/software/OpenMPI/4.1.4-GCC-11.3.0/bin/mpifort" 
export OPENMPI_CFLAGS="-I/share/myuser/software/x86_64/software/OpenMPI/4.1.4-GCC-11.3.0/include" 
export OPENMPI_LDFLAGS="-L/share/myuser/software/x86_64/software/OpenMPI/4.1.4-GCC-11.3.0/lib -L/share/myuser/software/x86_64/software/hwloc/2.7.1-GCCcore-11.3.0/lib -L/share/myuser/software/x86_64/software/libevent/2.1.12-GCCcore-11.3.0/lib -Wl,-rpath -Wl,/share/myuser/software/x86_64/software/OpenMPI/4.1.4-GCC-11.3.0/lib -Wl,-rpath -Wl,/share/myuser/software/x86_64/software/hwloc/2.7.1-GCCcore-11.3.0/lib -Wl,-rpath -Wl,/share/myuser/software/x86_64/software/libevent/2.1.12-GCCcore-11.3.0/lib -Wl,--enable-new-dtags " 
export OPENMPI_LIBS=" -lmpi" 
export MPI_CFLAGS="-I/share/myuser/software/x86_64/software/OpenMPI/4.1.4-GCC-11.3.0/include" 
export MPI_LDFLAGS="-L/share/myuser/software/x86_64/software/OpenMPI/4.1.4-GCC-11.3.0/lib -L/share/myuser/software/x86_64/software/hwloc/2.7.1-GCCcore-11.3.0/lib -L/share/myuser/software/x86_64/software/libevent/2.1.12-GCCcore-11.3.0/lib -Wl,-rpath -Wl,/share/myuser/software/x86_64/software/OpenMPI/4.1.4-GCC-11.3.0/lib -Wl,-rpath -Wl,/share/myuser/software/x86_64/software/hwloc/2.7.1-GCCcore-11.3.0/lib -Wl,-rpath -Wl,/share/myuser/software/x86_64/software/libevent/2.1.12-GCCcore-11.3.0/lib -Wl,--enable-new-dtags " 
export MPI_LIBS=" -lmpi" 
export CP_DFLAGS="${CP_DFLAGS} IF_MPI(-D__parallel|)" 
# For proper mpi_f08 support, we need at least GCC version 9 (asynchronous keyword)
# Other compilers should work
  if ! [ "11" -lt 9 ]; then
    export CP_DFLAGS="${CP_DFLAGS} IF_MPI(-D__MPI_F08|)" 
  fi
export CP_CFLAGS="${CP_CFLAGS} IF_MPI(-I/share/myuser/software/x86_64/software/OpenMPI/4.1.4-GCC-11.3.0/include|)" 
export CP_LDFLAGS="${CP_LDFLAGS} IF_MPI(-L/share/myuser/software/x86_64/software/OpenMPI/4.1.4-GCC-11.3.0/lib -L/share/myuser/software/x86_64/software/hwloc/2.7.1-GCCcore-11.3.0/lib -L/share/myuser/software/x86_64/software/libevent/2.1.12-GCCcore-11.3.0/lib -Wl,-rpath -Wl,/share/myuser/software/x86_64/software/OpenMPI/4.1.4-GCC-11.3.0/lib -Wl,-rpath -Wl,/share/myuser/software/x86_64/software/hwloc/2.7.1-GCCcore-11.3.0/lib -Wl,-rpath -Wl,/share/myuser/software/x86_64/software/libevent/2.1.12-GCCcore-11.3.0/lib -Wl,--enable-new-dtags |)" 
export CP_LIBS="${CP_LIBS} IF_MPI( -lmpi|)" 
export FFTW3_INCLUDES="-I'/share/myuser/software/x86_64/software/FFTW.MPI/3.3.10-gompi-2022a/include'" 
export FFTW3_LIBS="IF_MPI(-lfftw3_mpi|) -lfftw3 -lfftw3_omp" 
export FFTW_CFLAGS="-I'/share/myuser/software/x86_64/software/FFTW.MPI/3.3.10-gompi-2022a/include'" 
export FFTW_LDFLAGS="-L'/share/myuser/software/x86_64/software/FFTW.MPI/3.3.10-gompi-2022a/lib' -Wl,-rpath,'/share/myuser/software/x86_64/software/FFTW.MPI/3.3.10-gompi-2022a/lib'" 
export FFTW_LIBS="IF_MPI(-lfftw3_mpi|) -lfftw3 -lfftw3_omp" 
export CP_DFLAGS="${CP_DFLAGS} -D__FFTW3 IF_COVERAGE(IF_MPI(|-U__FFTW3)|)" 
export CP_CFLAGS="${CP_CFLAGS} -I'/share/myuser/software/x86_64/software/FFTW.MPI/3.3.10-gompi-2022a/include'" 
export CP_LDFLAGS="${CP_LDFLAGS} -L'/share/myuser/software/x86_64/software/FFTW.MPI/3.3.10-gompi-2022a/lib' -Wl,-rpath,'/share/myuser/software/x86_64/software/FFTW.MPI/3.3.10-gompi-2022a/lib'" 
export CP_LIBS="IF_MPI(-lfftw3_mpi|) -lfftw3 -lfftw3_omp ${CP_LIBS}" 
export FFTW_ROOT=
export FFTW3_ROOT=
prepend_path LD_LIBRARY_PATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libint-v2.6.0-cp2k-lmax-5/lib" 
prepend_path LD_RUN_PATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libint-v2.6.0-cp2k-lmax-5/lib" 
prepend_path LIBRARY_PATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libint-v2.6.0-cp2k-lmax-5/lib" 
prepend_path PKG_CONFIG_PATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libint-v2.6.0-cp2k-lmax-5/lib/pkgconfig" 
prepend_path CMAKE_PREFIX_PATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libint-v2.6.0-cp2k-lmax-5" 
export LIBINT2_ROOT="/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libint-v2.6.0-cp2k-lmax-5" 
prepend_path LD_LIBRARY_PATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libxc-6.2.2/lib" 
prepend_path LD_RUN_PATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libxc-6.2.2/lib" 
prepend_path LIBRARY_PATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libxc-6.2.2/lib" 
prepend_path CPATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libxc-6.2.2/include" 
prepend_path PKG_CONFIG_PATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libxc-6.2.2/lib/pkgconfig" 
prepend_path CMAKE_PREFIX_PATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libxc-6.2.2" 
prepend_path LD_LIBRARY_PATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libgrpp-main-20231215/lib" 
prepend_path LD_RUN_PATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libgrpp-main-20231215/lib" 
prepend_path LIBRARY_PATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libgrpp-main-20231215/lib" 
prepend_path PKG_CONFIG_PATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libgrpp-main-20231215/lib/pkgconfig" 
prepend_path CMAKE_PREFIX_PATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libgrpp-main-20231215" 
export LIBGRPP_ROOT="/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libgrpp-main-20231215" 
prepend_path PATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libxsmm-1.17/bin" 
prepend_path LD_LIBRARY_PATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libxsmm-1.17/lib" 
prepend_path LD_RUN_PATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libxsmm-1.17/lib" 
prepend_path LIBRARY_PATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libxsmm-1.17/lib" 
prepend_path PKG_CONFIG_PATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libxsmm-1.17/lib/pkgconfig" 
prepend_path LD_LIBRARY_PATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/spglib-1.16.2/lib" 
prepend_path LD_RUN_PATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/spglib-1.16.2/lib" 
prepend_path LIBRARY_PATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/spglib-1.16.2/lib" 
prepend_path CPATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/spglib-1.16.2/include" 
prepend_path PKG_CONFIG_PATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/spglib-1.16.2/lib/pkgconfig" 
prepend_path CMAKE_PREFIX_PATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/spglib-1.16.2" 
export SPGLIB_CFLAGS="-I/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/spglib-1.16.2/include -I/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/spglib-1.16.2/include" 
export SPGLIB_LDFLAGS="-L'/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/spglib-1.16.2/lib' -Wl,-rpath,'/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/spglib-1.16.2/lib'" 
export CP_DFLAGS="${CP_DFLAGS} -D__SPGLIB" 
export CP_CFLAGS="${CP_CFLAGS} -I/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/spglib-1.16.2/include" 
export CP_LDFLAGS="${CP_LDFLAGS} -L'/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/spglib-1.16.2/lib' -Wl,-rpath,'/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/spglib-1.16.2/lib'" 
export CP_LIBS="-lsymspg ${CP_LIBS}" 
export LIBSPG_ROOT="/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/spglib-1.16.2" 
export LIBSPG_INCLUDE_DIR="/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/spglib-1.16.2/include" 
prepend_path LD_LIBRARY_PATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libvori-220621/lib" 
prepend_path LD_RUN_PATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libvori-220621/lib" 
prepend_path LIBRARY_PATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libvori-220621/lib" 
export LIBVORI_LIBS="-lvori -lstdc++" 
export LIBVORI_ROOT="/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libvori-220621" 
prepend_path PKG_CONFIG_PATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libvori-220621/lib/pkgconfig" 
prepend_path CMAKE_PREFIX_PATH "/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libvori-220621" 
export LIBVORI_ROOT="/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libvori-220621" 
export LIBVORI_VERSION=220621
export LIBVORI_LDFLAGS="-L'/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libvori-220621/lib' -Wl,-rpath,'/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libvori-220621/lib'" 
export LIBVORI_LIBRARY="-lvori" 
export CP_DFLAGS="${CP_DFLAGS} -D__LIBVORI" 
export CP_LDFLAGS="${CP_LDFLAGS} -L'/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libvori-220621/lib' -Wl,-rpath,'/home/myuser/workspace_vidal/cp2k_repogit/tools/toolchain/install/libvori-220621/lib'" 
export CP_LIBS="${CP_LIBS} -lvori -lstdc++" 
``` 

I don't know if It is necessary or not but I modify the *DFLAGS parameter* with options `-D__PW_CUDA -D__ACC` (they are not there) and  I add the **NVCC path**  at the end of this file as you say here https://www.cp2k.org/howto:compile_with_cuda because It was not there 

```makefile
DFLAGS      = -D__OFFLOAD_CUDA -D__DBCSR_ACC  -D__LIBXSMM  -D__parallel -D__MPI_F08 -D__FFTW3  -D__LIBINT -D__LIBXC -D__LIBGRPP -D__SCALAPACK -D__SPGLIB -D__LIBVORI -D__PW_CUDA -D__ACC
NVCC    = /share/myuser/software/x86_64/software/CUDA/11.8.0/bin/nvcc
``` 
and the output of compile is this  [local_cuda_compile.txt](https://github.com/cp2k/cp2k/files/15162932/local_cuda_compile.txt)

With or without previous options `(-D__PW_CUDA -D__ACC) and NVCC = path` cp2k compile 

When I try to run cp2k

```shell
./cp2k.psmp --version    or
srun ./cp2k.psmp --version   or 
mpirun --bind-to core --map-by numa:PE=16 ./cp2k.psmp --help
``` 
 I get this issue:

```shell
ERROR: cuInit failed with error:  34 /home/myuser/workspace_vidal/cp2k_repogit/src/offload/offload_library.c 57

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x14da3af8ab1f in ???
#1  0x14da3af8aa9f in ???
#2  0x14da3af5de04 in ???
#3  0x317f48b in offload_init
	at /home/myuser/workspace_vidal/cp2k_repogit/src/offload/offload_library.c:58
#4  0xb173ff in __f77_interface_MOD_init_cp2k
	at /home/myuser/workspace_vidal/cp2k_repogit/src/f77_interface.F:234
#5  0x473233 in cp2k
	at /home/myuser/workspace_vidal/cp2k_repogit/src/start/cp2k.F:284
#6  0x41521c in main
	at /home/myuser/workspace_vidal/cp2k_repogit/src/start/cp2k.F:44
srun: error: node17104-1: task 0: Aborted (core dumped)
....
``` 
Seems like it is not able to find CUDA even though the build was successful.

The block code where I can see this error is in: 
 
> src/offload/offload_library.c

```c
....
void offload_init(void) {
#if defined(__OFFLOAD_CUDA)
  CUresult error = cuInit(0);
  if (error != CUDA_SUCCESS) {
    fprintf(stderr, "ERROR: %s %d %s %d\n", "cuInit failed with error: ", error,
            __FILE__, __LINE__);
    abort();
  }
#elif defined(__OFFLOAD_HIP)
  OFFLOAD_CHECK(hipInit(0));
#elif defined(__OFFLOAD_OPENCL)
  OFFLOAD_CHECK(c_dbcsr_acc_init());
#endif
}
``` 
CUDA is loaded and It is in the path and the driver works fine:

```shell
$ echo $PATH
/share/myuser/software/x86_64/software/CUDA/11.8.0/nvvm/bin:/share/myuser/software/x86_64/software/CUDA/11.8.0/bin:/share/myuser/software/x86_64/software/CMake/3.24.3-GCCcore-11.3.0/bin:/share/myuser/software/x86_64/software/FFTW/3.3.10-GCC-11.3.0/bin:/share/myuser/software/x86_64/software/libarchive/3.6.1-GCCcore-11.3.0/bin:/share/myuser/software/x86_64/software/cURL/7.83.0-GCCcore-11.3.0/bin:/share/myuser/software/x86_64/software/bzip2/1.0.8-GCCcore-11.3.0/bin:/share/myuser/software/x86_64/software/ncurses/6.3-GCCcore-11.3.0/bin:/share/myuser/software/x86_64/software/FlexiBLAS/3.2.0-GCC-11.3.0/bin:/share/myuser/software/x86_64/software/OpenMPI/4.1.4-GCC-11.3.0/bin:/share/myuser/software/x86_64/software/UCC/1.0.0-GCCcore-11.3.0/bin:/share/myuser/software/x86_64/software/PMIx/4.1.2-GCCcore-11.3.0/bin:/share/myuser/software/x86_64/software/libfabric/1.15.1-GCCcore-11.3.0/bin:/share/myuser/software/x86_64/software/UCX/1.12.1-GCCcore-11.3.0/bin:/share/myuser/software/x86_64/software/libevent/2.1.12-GCCcore-11.3.0/bin:/share/myuser/software/x86_64/software/OpenSSL/1.1/bin:/share/myuser/software/x86_64/software/hwloc/2.7.1-GCCcore-11.3.0/sbin:/share/myuser/software/x86_64/software/hwloc/2.7.1-GCCcore-11.3.0/bin:/share/myuser/software/x86_64/software/libxml2/2.9.13-GCCcore-11.3.0/bin:/share/myuser/software/x86_64/software/XZ/5.2.5-GCCcore-11.3.0/bin:/share/myuser/software/x86_64/software/numactl/2.0.14-GCCcore-11.3.0/bin:/share/myuser/software/x86_64/software/binutils/2.38-GCCcore-11.3.0/bin:/share/myuser/software/x86_64/software/GCCcore/11.3.0/bin:/home/myuser/.yarn/bin:/home/myuser/.config/yarn/global/node_modules/.bin:/share/myuser/software/common/software/Miniconda3/23.5.2-0/condabin:/home/myuser/.local/bin:/home/myuser/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
``` 

```shell
$ which nvcc
/share/myuser/software/x86_64/software/CUDA/11.8.0/bin/nvcc

$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

$ nvlink --version
nvlink: NVIDIA (R) Cuda linker
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

$ nvidia-smi
Tue Apr 30 13:13:35 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.13    Driver Version: 525.60.13    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-PCI...  On   | 00000000:17:00.0 Off |                    0 |
| N/A   28C    P0    35W / 250W |      0MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-PCI...  On   | 00000000:31:00.0 Off |                    0 |
| N/A   26C    P0    33W / 250W |      0MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A100-PCI...  On   | 00000000:B1:00.0 Off |                    0 |
| N/A   26C    P0    33W / 250W |      0MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA A100-PCI...  On   | 00000000:CA:00.0 Off |                    0 |
| N/A   26C    P0    33W / 250W |      0MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
``` 

I hope I have described my steps and my problem well.

Thanks in advance.

**Comment by hfp** [comment]
Looks similar to #3369.
