### ISSUE TITLE
prettify.py crashes because of logging Formatter

### ISSUE THREAD

**Issue by oschuett** [cp2k/cp2k#692]
The problem is that some log [messages]( 
https://github.com/cp2k/cp2k/blob/master/tools/prettify/prettify.py#L179) do not provide the fields required by the [installed formatter](https://github.com/cp2k/cp2k/blob/master/tools/prettify/prettify.py#L452).

Reproducer:
```
$ cd cp2k/src
$ ../tools/prettify/prettify.py qmmm_gpw_forces.F 
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 868, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 741, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 469, in format
    s = self._fmt % record.__dict__
KeyError: 'ffilename'
Logged from file prettify.py, line 181
```

**Comment by oschuett** [comment]
Thanks for the quick patch!
