### ISSUE TITLE
Segmentation Fault if PRINT_LEVEL is DEBUG

### ISSUE THREAD

**Issue by e-kwsm** [cp2k/cp2k#884]
* CP2K: version 7.1
* cp2kflags: libint fftw3 libxc xsmm spglib check_diag
* compiler and MPI: Intel 2018.2                

Segmentation fault occurs when `PRINT_LEVEL` is set to `DEBUG`.
This is not reproduced with CP2K 6.1 compiled with Intel 2017U8.

Input file:

```
&GLOBAL
  RUN_TYPE ENERGY
! PRINT_LEVEL MEDIUM  ! OK
! PRINT_LEVEL HIGH    ! OK
  PRINT_LEVEL DEBUG   ! error
&END GLOBAL
&FORCE_EVAL
  &DFT
    BASIS_SET_FILE_NAME EMSL_BASIS_SETS
    &POISSON
      PERIODIC NONE
      PSOLVER ANALYTIC
    &END POISSON
    &QS
      METHOD GAPW
    &END QS
    &XC
      &XC_FUNCTIONAL
        &PBE
        &END PBE
      &END XC_FUNCTIONAL
    &END XC
  &END DFT
  &SUBSYS
    &CELL
      ABC 4. 4. 4.
      PERIODIC NONE
    &END CELL
    &COORD
      He 0. 0. 0.
    &END COORD
    &KIND He
      BASIS_SET 3-21Gx
      POTENTIAL ALL
    &END KIND
  &END SUBSYS
&END FORCE_EVAL
```

```shellsession
$ gdb cp2k.sdbg
(gdb) run input
…
SYMMETRIZING RESULTS
     Final NS sqrt iter    4 1.00000000   0.229E-14

  Creating energy windows. Fermi level:  -0.551150601366536     
  Printing Energy Levels from  -0.551150601366536       to 
   1.67572675451522     
 Energy Level:    -0.5400162146 Number of states:     1 Occupation:     2.00000000000000
 Energy Level:    -0.5177474410 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:    -0.4954786675 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:    -0.4732098939 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:    -0.4509411204 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:    -0.4286723468 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:    -0.4064035732 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:    -0.3841347997 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:    -0.3618660261 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:    -0.3395972526 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:    -0.3173284790 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:    -0.2950597054 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:    -0.2727909319 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:    -0.2505221583 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:    -0.2282533848 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:    -0.2059846112 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:    -0.1837158376 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:    -0.1614470641 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:    -0.1391782905 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:    -0.1169095170 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:    -0.0946407434 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:    -0.0723719699 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:    -0.0501031963 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:    -0.0278344227 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:    -0.0055656492 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.0167031244 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.0389718979 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.0612406715 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.0835094451 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.1057782186 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.1280469922 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.1503157657 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.1725845393 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.1948533129 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.2171220864 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.2393908600 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.2616596335 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.2839284071 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.3061971806 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.3284659542 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.3507347278 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.3730035013 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.3952722749 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.4175410484 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.4398098220 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.4620785956 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.4843473691 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.5066161427 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.5288849162 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.5511536898 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.5734224634 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.5956912369 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.6179600105 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.6402287840 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.6624975576 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.6847663311 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.7070351047 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.7293038783 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.7515726518 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.7738414254 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.7961101989 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.8183789725 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.8406477461 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.8629165196 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.8851852932 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.9074540667 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.9297228403 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.9519916139 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.9742603874 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     0.9965291610 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     1.0187979345 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     1.0410667081 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     1.0633354816 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     1.0856042552 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     1.1078730288 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     1.1301418023 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     1.1524105759 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     1.1746793494 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     1.1969481230 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     1.2192168966 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     1.2414856701 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     1.2637544437 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     1.2860232172 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     1.3082919908 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     1.3305607644 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     1.3528295379 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     1.3750983115 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     1.3973670850 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     1.4196358586 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     1.4419046321 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     1.4641734057 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     1.4864421793 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     1.5087109528 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     1.5309797264 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     1.5532484999 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     1.5755172735 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     1.5977860471 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     1.6200548206 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     1.6423235942 Number of states:     0 Occupation:     0.00000000000000
 Energy Level:     1.6645923677 Number of states:     0 Occupation:     0.00000000000000

Program received signal SIGSEGV, Segmentation fault.
0x000000000132a18f in qs_local_properties_mp_qs_local_energy_ ()
(gdb) backtrace
#0  0x000000000132a18f in qs_local_properties_mp_qs_local_energy_ ()
#1  0x0000000000be0c2d in qs_scf_post_gpw_mp_qs_scf_post_local_energy_ ()
#2  0x0000000000bd80cd in qs_scf_post_gpw_mp_write_mo_free_results_ ()
#3  0x0000000000bc70cb in qs_scf_post_gpw_mp_scf_post_calculation_gpw_ ()
#4  0x000000000183cf59 in qs_scf_post_scf_mp_qs_scf_compute_properties_ ()
#5  0x0000000001270ea1 in qs_scf_mp_scf_ ()
#6  0x00000000011fbe39 in qs_energy_mp_qs_energies_ ()
#7  0x0000000000b6df03 in qs_force_mp_qs_calc_energy_force_ ()
#8  0x00000000008eec61 in force_env_methods_mp_force_env_calc_energy_force_ ()
#9  0x000000000042c048 in cp2k_runs_mp_run_input_ ()
#10 0x00000000004091ae in MAIN__ ()
#11 0x0000000009be5212 in main ()
```

**Comment by juerghutter** [comment]
Fixed with PR #885
